name:                tryhaskell
version:             0.1.0.0
github:              "githubuser/tryhaskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

default-extensions:
- "OverloadedStrings"
- "MultiWayIf"
- "BlockArguments"
- "ScopedTypeVariables"
- "LambdaCase"
- "RecordWildCards"
- "FlexibleContexts"
- "ViewPatterns"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tryhaskell#readme>

dependencies:
- base >= 4.7 && < 5
- duet
- warp
- wai
- mtl
- monad-logger
- exceptions
- bytestring
- text
- lucid2
- http-types
- safe-exceptions
- unliftio
- async
- containers
- unordered-containers
- stm

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  tryhaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tryhaskell

tests:
  tryhaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tryhaskell
