# fly.toml app configuration file generated for tryhaskell on 2023-06-04T20:35:36+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tryhaskell"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[build]
  image = "ghcr.io/chrisdone/tryhaskell@sha256:d968d8eb2a0f69099236c3fd9d088d14988b35e4a116f89169ca5296898bf757"
